language: node_js
node_js:
- 10
install:
- npm install
script:
- npm run cover
after_success: npm run coveralls
deploy:
  provider: npm
  email: scottdonald@protonmail.ch
  api_key:
    secure: JiyC8/zxN9jVpNxEuadU8UhyANk9nZm8l4iC3QDPdYLcHTlglJuZaBP+v0pa0XwysOsJPcJ4Wls4Kr+zzU/HPqi5CdtZpPlbHwZ4Sdx+pSEuQ5o4Md7TmyRTVUgLQs9Mjd5z0yx0N9JaDUldGPFoEQis7LFeF9V6UJ3sQr/FmJj9FdOvWo9QRHA1kgSDw4gycg/T7J1ZYP/q5FRMfin0htTReLqu3ElYLGT2aP79eNJjQMrtfmVXrspYKYl45IyzQXZrrAPd4UF1Nst+Agr9Fzm6nXVDj6ugJdde3HWqttX0irhBNvffGXfcCzHBv7oCa/2xHd4IDru2tCQPeWNBbP+bsMbHAxLR+qyW6icVZ7yM5vQ/uL8UZfKVYDpYtlJZLjtOGqDIxZ/lG1hhrOATshZTrgmaJSV0hVKF6HcT/Xe0EOcXJ+1/nNuqU7UpBM2u6sP9ChOiktTM/HQAMbcZUBRRDzaUsUSJWrVrZkCdeR336oa7v6aYUR3A19vHeCETj1caXg08vu8CorINC2lE7QnXgg22Q956Vue0uTwfpnKSESZ9/q97TtB1MV57kLkYcfb5KWr1mR74DAyQ2f3M9K5qA7J97YYj/H9LRqdVcW6PMcLyA0ds7grdsWeAQGrOEIxfN3Xb8zk2fUWUPQdyiNHGnnBAQh1oS/IoOnbvbz4=
  on:
    tags: true
    branch: master
